### ISSUE TITLE
which format for the stream is used?

### ISSUE THREAD

**Issue by Freundschaft** [audiojs/audio-spectrum#2]
as far as I understand the source code, it should be possible to directly pipe a PCM stream to the spectrum.

However when I try to pipe a microphone stream from https://github.com/Freundschaft/node-microphone

with

`var mic = require('microphone');

mic.startCapture()
mic.audioStream
   .pipe(plotter);`

I dont see any signal in the spectrum. Do I need to do any kind of conversions in between?

Thanks!

**Comment by dy** [comment]
Hi!
Please use [gl-spectrum](http://github.com/audio-lab/gl-spectrum) in the meantime, as this component is outdated

**Comment by dy** [comment]
Or if you want to use it in node I am afraid there is no option for now but implementing your own spectrum.

**Comment by Freundschaft** [comment]
alright, thanks!
